### ISSUE TITLE
breaks with webpack > 4

### ISSUE THREAD

**Issue by basaran** [gabiseabra/google-fonts-webpack-plugin#36] opened 2020-11-26 09:25 UTC
Hello, it appears `gabiseabra/google-fonts-webpack-plugin` breaks with webpack 4. Could you please update the README?

This seems to be the default root package for `google-fonts-webpack-plugin` so, there is probably quite a few people who try this first like me and go into a debugging cycle.

```
yarn run v1.22.4                                                                          
$ vue-cli-service serve                                                                    
INFO  Starting development server...
10% building 2/2 modules 0 active(node:29517) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead       
```

`beyonk-adventures/google-fonts-webpack-plugin` is compatible with webpack > 4.

[https://github.com/webpack/webpack/issues/6568](https://github.com/webpack/webpack/issues/6568)

**Comment by Rycochet** [comment] 2020-11-27 06:22
Duplicate of #24 from more than two years ago

**Comment by basaran** [comment] 2020-11-28 07:48
My request was to include this in the README. So, when someone has an issue and visits the github page, they could be alarmed as to why. This is the package that gets installed by default when you to npm or yarn without the repo prefix. It will probably make somebody's life easier.

**Closed as completed** 2021-11-07 22:10 UTC
